backend:
    name: github
    branch: master
    repo: lekevoid/lekevoid-recipes
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: editorial_workflow

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
    - label: "Recipes"
      name: "recipes"
      folder: "src/recipes"
      create: true
      editor:
          preview: false
      fields:
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Feature Image", name: "feature_image", widget: "image", required: false }
          - { label: "Time to make (minutes)", name: "time", widget: "number", required: false }
          - { label: "Complexity", name: "complexity", widget: "number", min: 1, max: 3, required: false }
          - label: "Categories"
            name: "categories"
            widget: "select"
            multiple: true
            required: false
            options:
                - { value: "breads", label: "Breads" }
                - { value: "dessert", label: "Dessert" }
                - { value: "main_courses", label: "Main Courses" }
                - { value: "salads", label: "Salads" }
                - { value: "side_dishes", label: "Side Dishes" }
                - { value: "smoothies", label: "Smoothies" }
                - { value: "soups", label: "Soups" }
          - label: "Origin"
            name: "origin"
            widget: "select"
            required: false
            options:
                - { value: "non_specific", label: "Non-Specific" }
                - { value: "chinese", label: "Chinese" }
                - { value: "european", label: "European" }
                - { value: "indian", label: "Indian" }
                - { value: "japanese", label: "Japanese" }
                - { value: "korean", label: "Korean" }
                - { value: "morroccan", label: "Morroccan" }
                - { value: "russian", label: "Russian" }
                - { value: "south_american", label: "South American" }
                - { value: "swedish", label: "Swedish" }
                - { value: "thai", label: "Thai" }
          - label: "Ingredients"
            name: "ingredients"
            widget: "list"
            allow_add: true
            required: false
            fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Quantity", name: "quantity", widget: "string", required: false }
                - {
                      label: "Measure",
                      name: "measure",
                      widget: "select",
                      options: ["Whole", "Some", "kg", "g", "lb", "cup", "tbsp", "tsp", "Pinch", "Can"],
                      required: false,
                  }
                - { label: "Comment", name: "comment", widget: "string", required: false }
          - { label: "Preparation", name: "preparation_steps", widget: "markdown" }
          - label: "Tags"
            name: "tags"
            widget: "select"
            required: false
            options:
                - { value: "meat", label: "Meat" }
                - { value: "vegan", label: "Vegan" }
                - { value: "vegetarian", label: "Vegetarian" }
          - label: "Reference Links"
            name: "reference"
            widget: "list"
            allow_add: true
            required: false
            fields:
                - { label: "Link", name: "link", widget: "string" }
    - label: "Settings"
      name: "settings"
      editor:
          preview: false
      files:
          - label: "Navigation"
            name: "items"
            file: "src/_data/navigation.yaml"
            fields:
                - label: Nav Items
                  name: items
                  widget: list
                  allow_add: false
                  collapsed: false
                  fields:
                      - { label: Title, name: text, widget: string }
                      - { label: URL, name: url, widget: string }
          - label: "Quick Links"
            name: "links"
            file: "src/_data/quicklinks.yaml"
            fields:
                - label: Nav Items
                  name: links
                  widget: list
                  collapsed: false
                  fields:
                      - { label: Title, name: title, widget: string }
                      - { label: URL, name: url, widget: string }
                      - { label: Description, name: desc, widget: string }
          - label: "Meta Settings"
            name: "settings"
            file: "src/_data/settings.yaml"
            fields:
                - { label: Name, name: name, widget: string }
                - { label: Author, name: author, widget: string }
                - { label: URL, name: url, widget: string }
